{% set name = "climada" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/climada-{{ version }}.tar.gz
  sha256: 5b5847afa5c37fa84ea574bbc4cd02a4bf0de55eebcece4319323f22bef1c46b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9,<3.12
    - pip
    - setuptools-scm
  run:
    - bayesian-optimization =1.5
    - bottleneck =1.3
    - cartopy =0.22
    - cfgrib =0.9.9
    - contextily =1.5
    - dask =2024.1
    - deprecation =2.1
    - eccodes =2.27
    - gdal =3.6
    - geopandas =0.14
    - h5py =3.8
    - haversine =2.8
    - matplotlib-base =3.8
    - netcdf4 =1.6
    - numba =0.59
    - numexpr =2.9
    - openpyxl =3.1
    - overpy =0.7
    - pandas =2.1
    - pandas-datareader =0.10
    - pathos =0.3
    - peewee =3.17
    - pillow =9.4
    - pint =0.23
    - pycountry =22.3
    - pyepsg =0.4
    - pyproj =3.5
    - pytables =3.7
    - python >=3.9,<3.12
    - pyxlsb =1.0
    - rasterio =1.3
    - requests =2.31
    - salib =1.4
    - scikit-learn =1.4
    - scipy =1.12
    - seaborn =0.13
    - sparse =0.15
    - statsmodels =0.14
    - tabulate =0.9
    - tqdm =4.66
    - unittest-xml-reporting =3.2
    - xarray =2024.1
    - xlrd =2.0
    - xlsxwriter =3.1
    - xmlrunner =1.7

test:
  imports:
    - climada
  source_files:
    - climada
  commands:
    - pip check
    - python3 -m unittest climada.engine.test.test_impact
  requires:
    - pip

about:
  home: https://github.com/CLIMADA-project/climada_python
  summary: "CLIMADA: Probabilistic natural catastrophe impact model in Python"
  description: |
    CLIMADA stands for CLIMate ADAptation and is a probabilistic natural catastrophe
    impact model, that also calculates averted damage (benefit) thanks to adaptation
    measures of any kind.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://climada-python.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - peanutfun
