{% set name = "climada" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/climada-{{ version }}.tar.gz
  sha256: 5c01494409a7c0d947b8b55d89326bf6a67e4883403ff0675949366e0c0f9303

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python =3.9
    - pip
  run:
    - bottleneck =1.3
    - cartopy =0.21
    - cfgrib =0.9.9
    - contextily =1.3
    - dask =2023
    - deprecation =2.1
    - eccodes =2.27
    - gdal =3.6
    - geopandas =0.13
    - h5py =3.8
    - haversine =2.8
    - matplotlib-base =3.7
    - netcdf4 =1.6
    - numba =0.57
    - openpyxl =3.1
    - overpy =0.6
    - pandas =1.5
    - pandas-datareader =0.10
    - pathos =0.3
    - peewee =3.16
    - pint =0.22
    - proj =9.1
    - pycountry =22.3
    - pyepsg =0.4
    - pytables =3.7
    - python =3.9
    - pyxlsb =1.0
    - rasterio =1.3
    - requests =2.31
    - salib =1.4
    - scikit-learn =1.2
    - scipy =1.10
    - sparse =0.14
    - statsmodels =0.14
    - tabulate =0.9
    - tqdm =4.65
    - unittest-xml-reporting =3.2
    - xarray =2023.5
    - xlrd =2.0
    - xlsxwriter =3.1
    - xmlrunner =1.7

test:
  imports:
    - climada
  source_files:
    - climada
    - data
  commands:
    - pip check
    - python3 -m unittest climada.engine.test.test_impact
  requires:
    - pip

about:
  home: https://github.com/CLIMADA-project/climada_python
  summary: "CLIMADA: Probabilistic natural catastrophe impact model in Python"
  description: |
    CLIMADA stands for CLIMate ADAptation and is a probabilistic natural catastrophe
    impact model, that also calculates averted damage (benefit) thanks to adaptation
    measures of any kind.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://climada-python.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - peanutfun
