{% set name = "climada" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/climada-{{ version }}.tar.gz
  sha256: cda2596f507c8da881a5371665ec1187eb5be90483204f365bb4e92f0614be95

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }},<3.13
    - bayesian-optimization =1.5
    - bottleneck =1.6
    - cartopy =0.25
    - cfgrib =0.9
    - contextily =1.6
    - dask =2025.9
    - deprecation =2.1
    - eccodes >=2.41
    - fiona =1.10
    - gdal =3.10
    - geopandas =1.1
    - h5py =3.13
    - haversine =2.9
    - lxml =6.0
    - matplotlib-base =3.10
    - netcdf4 =1.7
    - numba =0.62
    - numexpr =2.13
    - openpyxl =3.1
    - osm-flex =1.1
    - overpy =0.7
    - pandas =2.1
    - pathos =0.3
    - peewee =3.18
    - pillow >=10.4,<11.4
    - pint =0.24
    - pyarrow >=20.0,<21.1
    - pycountry =24.6
    - pyproj =3.7
    - pytables =3.10
    - pyxlsb =1.0
    - rasterio =1.4
    - requests =2.32
    - rtree =1.4
    - salib =1.5
    - scikit-learn =1.7
    - scipy =1.15
    - seaborn =0.13
    - sparse =0.17
    - statsmodels =0.14
    - tabulate =0.9
    - tqdm =4.67
    - unittest-xml-reporting =3.2
    - xarray =2025.6
    - xlrd =2.0
    - xlsxwriter =3.2

test:
  imports:
    - climada
  source_files:
    - climada
  commands:
    - pip check
    - python3 -m unittest climada.engine.test.test_impact
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CLIMADA-project/climada_python
  summary: "CLIMADA: Probabilistic natural catastrophe impact model in Python"
  description: |
    CLIMADA (CLIMate ADAptation) is a free and open-source software framework
    for climate risk assessment and adaptation option appraisal. Designed by a
    large scientific community, it helps reasearchers, policymakers, and
    businesses analyse the impacts of natural hazards and explore adaptation
    strategies. 
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://climada-python.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - emanuel-schmid
    - peanutfun
