{% set name = "climada" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/climada-{{ version }}.tar.gz
  sha256: ea8ef811aaa167a9864a79c753d1423c5b660d92ba179b2bd788e51fd9bcca2f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }},<3.12
    - bayesian-optimization =1.5
    - bottleneck =1.4
    - cartopy =0.24
    - cfgrib =0.9
    - contextily =1.6
    - dask =2025.2
    - deprecation =2.1
    - eccodes =2.40
    - gdal =3.10
    - geopandas =0.14
    - h5py =3.12
    - haversine =2.9
    - matplotlib-base =3.10
    - netcdf4 =1.7
    - numba =0.61
    - numexpr =2.10
    - openpyxl =3.1
    - osm-flex =1.1
    - overpy =0.7
    - pandas =2.1
    - pandas-datareader =0.10
    - pathos =0.3
    - peewee =3.17
    - pillow =10.4
    - pint =0.24
    - pycountry =24.6
    - pyproj =3.7
    - pytables =3.10
    - pyxlsb =1.0
    - rasterio =1.4
    - requests =2.32
    - rtree =1.3
    - salib =1.5
    - scikit-learn =1.6
    - scipy =1.14
    - seaborn =0.13
    - sparse =0.15
    - statsmodels =0.14
    - tabulate =0.9
    - tqdm =4.67
    - unittest-xml-reporting =3.2
    - xarray =2025.1
    - xlrd =2.0
    - xlsxwriter =3.2

test:
  imports:
    - climada
  source_files:
    - climada
  commands:
    - pip check
    - python3 -m unittest climada.engine.test.test_impact
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CLIMADA-project/climada_python
  summary: "CLIMADA: Probabilistic natural catastrophe impact model in Python"
  description: |
    CLIMADA (CLIMate ADAptation) is a free and open-source software framework
    for climate risk assessment and adaptation option appraisal. Designed by a
    large scientific community, it helps reasearchers, policymakers, and
    businesses analyse the impacts of natural hazards and explore adaptation
    strategies. 
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://climada-python.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - emanuel-schmid
    - peanutfun
